// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ApprovalHandler is an autogenerated mock type for the ApprovalHandler type
type ApprovalHandler struct {
	mock.Mock
}

// ApprovalDetail provides a mock function with given fields:
func (_m *ApprovalHandler) ApprovalDetail() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// EmployeeApprovalRecord provides a mock function with given fields:
func (_m *ApprovalHandler) EmployeeApprovalRecord() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetApproval provides a mock function with given fields:
func (_m *ApprovalHandler) GetApproval() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// PostApproval provides a mock function with given fields:
func (_m *ApprovalHandler) PostApproval() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// UpdateApproval provides a mock function with given fields:
func (_m *ApprovalHandler) UpdateApproval() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewApprovalHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewApprovalHandler creates a new instance of ApprovalHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApprovalHandler(t mockConstructorTestingTNewApprovalHandler) *ApprovalHandler {
	mock := &ApprovalHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
