// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	attendance "timesync-be/features/attendance"

	mock "github.com/stretchr/testify/mock"
)

// AttendanceData is an autogenerated mock type for the AttendanceData type
type AttendanceData struct {
	mock.Mock
}

// AttendanceFromAdmin provides a mock function with given fields: adminID, dateStart, dateEnd, attendanceType, employeeID
func (_m *AttendanceData) AttendanceFromAdmin(adminID uint, dateStart string, dateEnd string, attendanceType string, employeeID uint) error {
	ret := _m.Called(adminID, dateStart, dateEnd, attendanceType, employeeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, string, string, uint) error); ok {
		r0 = rf(adminID, dateStart, dateEnd, attendanceType, employeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClockIn provides a mock function with given fields: employeeID, latitudeData, longitudeData
func (_m *AttendanceData) ClockIn(employeeID uint, latitudeData string, longitudeData string) (attendance.Core, error) {
	ret := _m.Called(employeeID, latitudeData, longitudeData)

	var r0 attendance.Core
	if rf, ok := ret.Get(0).(func(uint, string, string) attendance.Core); ok {
		r0 = rf(employeeID, latitudeData, longitudeData)
	} else {
		r0 = ret.Get(0).(attendance.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, string) error); ok {
		r1 = rf(employeeID, latitudeData, longitudeData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClockOut provides a mock function with given fields: employeeID, latitudeData, longitudeData
func (_m *AttendanceData) ClockOut(employeeID uint, latitudeData string, longitudeData string) (attendance.Core, error) {
	ret := _m.Called(employeeID, latitudeData, longitudeData)

	var r0 attendance.Core
	if rf, ok := ret.Get(0).(func(uint, string, string) attendance.Core); ok {
		r0 = rf(employeeID, latitudeData, longitudeData)
	} else {
		r0 = ret.Get(0).(attendance.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, string) error); ok {
		r1 = rf(employeeID, latitudeData, longitudeData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPresenceDetail provides a mock function with given fields: adminID, attendanceID
func (_m *AttendanceData) GetPresenceDetail(adminID uint, attendanceID uint) (attendance.Core, error) {
	ret := _m.Called(adminID, attendanceID)

	var r0 attendance.Core
	if rf, ok := ret.Get(0).(func(uint, uint) attendance.Core); ok {
		r0 = rf(adminID, attendanceID)
	} else {
		r0 = ret.Get(0).(attendance.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(adminID, attendanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPresenceToday provides a mock function with given fields: employeeID
func (_m *AttendanceData) GetPresenceToday(employeeID uint) (attendance.Core, error) {
	ret := _m.Called(employeeID)

	var r0 attendance.Core
	if rf, ok := ret.Get(0).(func(uint) attendance.Core); ok {
		r0 = rf(employeeID)
	} else {
		r0 = ret.Get(0).(attendance.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(employeeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPresenceTotalToday provides a mock function with given fields: adminID
func (_m *AttendanceData) GetPresenceTotalToday(adminID uint) ([]attendance.Core, error) {
	ret := _m.Called(adminID)

	var r0 []attendance.Core
	if rf, ok := ret.Get(0).(func(uint) []attendance.Core); ok {
		r0 = rf(adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attendance.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Record provides a mock function with given fields: employeeID, dateFrom, dateTo
func (_m *AttendanceData) Record(employeeID uint, dateFrom string, dateTo string) ([]attendance.Core, error) {
	ret := _m.Called(employeeID, dateFrom, dateTo)

	var r0 []attendance.Core
	if rf, ok := ret.Get(0).(func(uint, string, string) []attendance.Core); ok {
		r0 = rf(employeeID, dateFrom, dateTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attendance.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, string) error); ok {
		r1 = rf(employeeID, dateFrom, dateTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAttendanceData interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttendanceData creates a new instance of AttendanceData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttendanceData(t mockConstructorTestingTNewAttendanceData) *AttendanceData {
	mock := &AttendanceData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
