// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	company "timesync-be/features/company"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// CompanyService is an autogenerated mock type for the CompanyService type
type CompanyService struct {
	mock.Mock
}

// EditProfile provides a mock function with given fields: token, fileData, updateData
func (_m *CompanyService) EditProfile(token interface{}, fileData multipart.FileHeader, updateData company.Core) (company.Core, error) {
	ret := _m.Called(token, fileData, updateData)

	var r0 company.Core
	if rf, ok := ret.Get(0).(func(interface{}, multipart.FileHeader, company.Core) company.Core); ok {
		r0 = rf(token, fileData, updateData)
	} else {
		r0 = ret.Get(0).(company.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, multipart.FileHeader, company.Core) error); ok {
		r1 = rf(token, fileData, updateData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields:
func (_m *CompanyService) GetProfile() (company.Core, error) {
	ret := _m.Called()

	var r0 company.Core
	if rf, ok := ret.Get(0).(func() company.Core); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(company.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCompanyService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompanyService creates a new instance of CompanyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompanyService(t mockConstructorTestingTNewCompanyService) *CompanyService {
	mock := &CompanyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
