// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	setting "timesync-be/features/setting"

	mock "github.com/stretchr/testify/mock"
)

// SettingData is an autogenerated mock type for the SettingData type
type SettingData struct {
	mock.Mock
}

// EditSetting provides a mock function with given fields: userID, updateSetting
func (_m *SettingData) EditSetting(userID uint, updateSetting setting.Core) (setting.Core, error) {
	ret := _m.Called(userID, updateSetting)

	var r0 setting.Core
	if rf, ok := ret.Get(0).(func(uint, setting.Core) setting.Core); ok {
		r0 = rf(userID, updateSetting)
	} else {
		r0 = ret.Get(0).(setting.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, setting.Core) error); ok {
		r1 = rf(userID, updateSetting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSetting provides a mock function with given fields:
func (_m *SettingData) GetSetting() (setting.Core, error) {
	ret := _m.Called()

	var r0 setting.Core
	if rf, ok := ret.Get(0).(func() setting.Core); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(setting.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSettingData interface {
	mock.TestingT
	Cleanup(func())
}

// NewSettingData creates a new instance of SettingData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSettingData(t mockConstructorTestingTNewSettingData) *SettingData {
	mock := &SettingData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
